CREATE TABLE [dbo].[Product](	
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 	
(	
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[Customer](	
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 	
(	
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[Supplier](	
	[SupplierID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Supplier] PRIMARY KEY CLUSTERED 	
(	
	[SupplierID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[Purchase](	
	[PurchaseID] [int] IDENTITY(1,1) NOT NULL,
	[No] [varchar](25) NOT NULL,
	[Date] [datetime] NOT NULL,
	[SupplierID] [int] NOT NULL,
 CONSTRAINT [PK_Purchase] PRIMARY KEY CLUSTERED 	
(	
	[PurchaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[PurchaseDetail](	
	[PurchaseDetailID] [int] IDENTITY(1,1) NOT NULL,
	[PurchaseID] [int] NOT NULL,
	[ProductID] [varchar](25) NOT NULL,
	[Quantity] [smallint] NOT NULL,
 CONSTRAINT [PK_PurchaseDetail] PRIMARY KEY CLUSTERED 	
(	
	[PurchaseDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[Sales](	
	[SalesID] [int] IDENTITY(1,1) NOT NULL,
	[No] [varchar](25) NOT NULL,
	[Date] [datetime] NOT NULL,
	[CustomerID] [int] NOT NULL,
 CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED 	
(	
	[SalesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
CREATE TABLE [dbo].[SalesDetail](	
	[SalesDetailID] [int] IDENTITY(1,1) NOT NULL,
	[SalesID] [int] NOT NULL,
	[ProductID] [varchar](25) NOT NULL,
	[Quantity] [smallint] NOT NULL,
 CONSTRAINT [PK_SalesDetail] PRIMARY KEY CLUSTERED 	
(	
	[SalesDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
) ON [PRIMARY]	
GO	
	
DECLARE @ID INT	
INSERT INTO Sales VALUES ('S240001', '7/1/24 11:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 300)	
INSERT INTO SalesDetail VALUES (@ID, 3, 120)	
INSERT INTO SalesDetail VALUES (@ID, 5, 210)	
	
INSERT INTO Sales VALUES ('S240002', '7/2/24 11:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 2, 730)	
INSERT INTO SalesDetail VALUES (@ID, 3, 320)	
INSERT INTO SalesDetail VALUES (@ID, 4, 240)	
	
INSERT INTO Sales VALUES ('S240003', '7/3/24 11:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 4, 90)	
INSERT INTO SalesDetail VALUES (@ID, 3, 590)	
INSERT INTO SalesDetail VALUES (@ID, 5, 620)	
	
INSERT INTO Sales VALUES ('S240004', '7/4/24 11:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 385)	
INSERT INTO SalesDetail VALUES (@ID, 2, 175)	
INSERT INTO SalesDetail VALUES (@ID, 5, 280)	
	
INSERT INTO Sales VALUES ('S240005', '7/5/24 11:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 430)	
INSERT INTO SalesDetail VALUES (@ID, 3, 610)	
INSERT INTO SalesDetail VALUES (@ID, 4, 310)	
	
INSERT INTO Sales VALUES ('S240006', '7/6/24 11:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 200)	
INSERT INTO SalesDetail VALUES (@ID, 2, 420)	
INSERT INTO SalesDetail VALUES (@ID, 3, 300)	
	
INSERT INTO Sales VALUES ('S240007', '7/14/24 11:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 385)	
INSERT INTO SalesDetail VALUES (@ID, 2, 175)	
INSERT INTO SalesDetail VALUES (@ID, 4, 280)	
	
INSERT INTO Sales VALUES ('S240008', '7/15/24 11:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 1, 430)	
INSERT INTO SalesDetail VALUES (@ID, 5, 610)	
INSERT INTO SalesDetail VALUES (@ID, 4, 310)	
	
INSERT INTO Sales VALUES ('S240009', '7/16/24 11:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO SalesDetail VALUES (@ID, 4, 200)	
INSERT INTO SalesDetail VALUES (@ID, 2, 420)	
INSERT INTO SalesDetail VALUES (@ID, 3, 300)	
	
GO	
	
DECLARE @ID INT	
INSERT INTO Purchase VALUES ('S240001', '7/1/24 09:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 400)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 220)	
INSERT INTO PurchaseDetail VALUES (@ID, 5, 310)	
	
INSERT INTO Purchase VALUES ('S240002', '7/2/24 09:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 2, 830)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 420)	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 340)	
	
INSERT INTO Purchase VALUES ('S240003', '7/3/24 09:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 190)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 690)	
INSERT INTO PurchaseDetail VALUES (@ID, 5, 720)	
	
INSERT INTO Purchase VALUES ('P240004', '7/4/24 09:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 485)	
INSERT INTO PurchaseDetail VALUES (@ID, 2, 275)	
INSERT INTO PurchaseDetail VALUES (@ID, 5, 380)	
	
INSERT INTO Purchase VALUES ('P240005', '7/5/24 09:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 530)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 710)	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 410)	
	
INSERT INTO Purchase VALUES ('P240006', '7/6/24 09:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 300)	
INSERT INTO PurchaseDetail VALUES (@ID, 2, 520)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 200)	
	
INSERT INTO Purchase VALUES ('P240007', '7/14/24 09:00:00', 3)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 485)	
INSERT INTO PurchaseDetail VALUES (@ID, 2, 275)	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 380)	
	
INSERT INTO Purchase VALUES ('P240008', '7/15/24 09:00:00', 2)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 1, 530)	
INSERT INTO PurchaseDetail VALUES (@ID, 5, 710)	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 510)	
	
INSERT INTO Purchase VALUES ('P240009', '7/16/24 09:00:00', 1)	
SET @ID = SCOPE_IDENTITY()	
INSERT INTO PurchaseDetail VALUES (@ID, 4, 300)	
INSERT INTO PurchaseDetail VALUES (@ID, 2, 520)	
INSERT INTO PurchaseDetail VALUES (@ID, 3, 400)	
